train:
  Resize:
    - 224
    - 224
  ColorJitter:
  RandomVerticalFlip:
  ToTensor:
  RandomErasing:

val:
  Resize:
    - 224
    - 224
  ToTensor:

test:
  Resize:
    - 224
    - 224
  ToTensor:

predict:
  Resize:
    - 224
    - 224
  ToTensor: